version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/blukai/animu
    steps:
      - checkout
      - save_cache:
          key: animu-{{ epoch }}
          paths:
            - /go

  test_bakkuendo:
    docker:
      - image: golang
      - image: olalond3/fakes3
    working_directory: /go/src/github.com/blukai/animu/bakkuendo
    steps:
      - run: rm -rf /go
      - restore_cache:
          key: animu
      - run:
          name: Install dep and dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
      - run: make test

  test_apuri:
    docker:
      - image: node
    working_directory: /go/src/github.com/blukai/animu/apuri
    steps:
      - restore_cache:
          key: animu
      - run: npm install
      - run: npm test

workflows:
  version: 2
  animu:
    jobs:
      - checkout_code

      - test_bakkuendo:
          requires:
            - checkout_code

      - test_apuri:
          requires:
            - checkout_code
