version: 2

jobs:
  checkout:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/blukai/animu
    steps:
      - checkout

  setup_bakkuendo_environment:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/blukai/animu/bakkuendo
    steps:
      - run: |
          pwd
          ls -al
      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
      #       chmod +x ~/docker-compose
      #       sudo mv ~/docker-compose /usr/local/bin/docker-compose
      # - setup_remote_docker
      # - run:
      #     name: Start containers
      #     command: |
      #       set -x
      #       docker-compose up -d
      # - run:
      #     name: Install dep
      #     command: |
      #       go get -u github.com/golang/dep/cmd/dep
      #       dep ensure

workflows:
  version: 2
  animu:
    jobs:
      - checkout
      - setup_bakkuendo_environment:
          requires:
            - checkout
